### ISSUE TITLE
请问这个dla与原先的dla有什么区别吗？

### ISSUE THREAD

**Issue by Senwang98** [DuZzzs/monodleX#1]
![image](https://user-images.githubusercontent.com/23122139/149540554-fbcc47b5-301e-4bd1-99cb-e6ce9fac733a.png)

**Comment by DuZzzs** [comment]
区别有：1）环境差异，这里在torch1.7.0下跑的；2）对原本代码中loss偶尔为nan做了修复。

**Comment by Senwang98** [comment]
@DuZzzs 
原来的bs=16，现在bs=6，但是学习率没变，如果从pytorch比较的角度来看，有没有可能换成bs=16，pt1.7会下降啊

**Comment by DuZzzs** [comment]
学习率有试过，波动不大。如果下降可能是DP带来的，这里表格只是说明在kitti上训练波动较大。

**Comment by Senwang98** [comment]
@DuZzzs 
了解了，没啥问题了。我记得我当时用pt1.7去训练，似乎精度没啥变化的

**Comment by Senwang98** [comment]
@DuZzzs 
老哥，我看了你的第一个commit（我觉得修改的还是很方便后续使用的，感谢开源）`test pretrain model`。我想问一下你现在的data结构树张什么样子以及为啥做这个commit设计，因为monodle以往的版本支持了-e做推理。

另外，其实monodle这边的IO不是很快，我对比过PIL与opencv的效率问题（同时读取一张图，除了RGB通道不一样，数值上会有个别的像素存在值为1的差距），慢很多。

**Comment by DuZzzs** [comment]
我的目录下没有`object`这一层，所以就改了下代码。
一般不同库读进来的会存在差异，保持和测试使用相同库就行，我在其他版本中用的opencv。

**Comment by DuZzzs** [comment]
@Senwang98 第一个commit应该只是测试下代码有没有问题，没其他意思。-_-
