### ISSUE TITLE
自己的数据集上测试效果很差

### ISSUE THREAD

**Issue by kuangcaomvp** [DuZzzs/monodleX#10]
作者你好，我用官方的monodle提供的模型和自己重新用kitti数据集训练的模型在kitti city数据集上测试效果很好，但是在自己采集的数据集上测试效果就很差，请问下这个是什么原因
![11](https://user-images.githubusercontent.com/26867020/203890103-be2d708d-5d6e-4fa3-aa90-8e3916f0a5d4.png)
我用的是1920 1080的图片做的测试，感觉中心点坐标偏移的很严重。

**Comment by DuZzzs** [comment]
两个相机内参不一样，相机坐标系下的3dbox位置和内参有关的。

**Comment by kuangcaomvp** [comment]
> 两个相机内参不一样，相机坐标系下的3dbox位置和内参有关的。

非常感谢您的回复，内参我改了的，用的是autoware标定的相机内参，我用smoke和smoke提供的模型测试自己的数据集3dbox效果就很好，monodle出现这种现象就很困惑，还有其他的可能性么，谢谢。

**Comment by DuZzzs** [comment]
建议训练集和测试集内参保持一致。
