### ISSUE TITLE
复现精度很高

### ISSUE THREAD

**Issue by wenjun1031** [DuZzzs/monodleX#7]
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:98.5218, 92.2878, 82.8832
bev  AP:30.7260, 22.9492, 19.8986
3d   AP:22.9616, 17.5276, 14.8316
aos  AP:97.73, 91.04, 80.95

**Comment by wenjun1031** [comment]
![image](https://user-images.githubusercontent.com/108816362/180784975-0f3fe435-6e79-4750-bcea-f790f06dabf9.png)

**Comment by YinengXiong** [comment]
您好，可以分享一下您的config以及相应的代码改动吗？
